// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TheFactorM.Federation {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("AccessControlServiceSignInController")]
	public partial class AccessControlServiceSignInController {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UITableView __mt_identityProviderList;
		
		private MonoTouch.UIKit.UIActivityIndicatorView __mt_progressIndicator;
		
		private MonoTouch.UIKit.UILabel __mt_subTitle;
		
		private MonoTouch.UIKit.UIWebView __mt_webBrowser;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("identityProviderList")]
		private MonoTouch.UIKit.UITableView identityProviderList {
			get {
				this.__mt_identityProviderList = ((MonoTouch.UIKit.UITableView)(this.GetNativeField("identityProviderList")));
				return this.__mt_identityProviderList;
			}
			set {
				this.__mt_identityProviderList = value;
				this.SetNativeField("identityProviderList", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("progressIndicator")]
		private MonoTouch.UIKit.UIActivityIndicatorView progressIndicator {
			get {
				this.__mt_progressIndicator = ((MonoTouch.UIKit.UIActivityIndicatorView)(this.GetNativeField("progressIndicator")));
				return this.__mt_progressIndicator;
			}
			set {
				this.__mt_progressIndicator = value;
				this.SetNativeField("progressIndicator", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("subTitle")]
		private MonoTouch.UIKit.UILabel subTitle {
			get {
				this.__mt_subTitle = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("subTitle")));
				return this.__mt_subTitle;
			}
			set {
				this.__mt_subTitle = value;
				this.SetNativeField("subTitle", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("webBrowser")]
		private MonoTouch.UIKit.UIWebView webBrowser {
			get {
				this.__mt_webBrowser = ((MonoTouch.UIKit.UIWebView)(this.GetNativeField("webBrowser")));
				return this.__mt_webBrowser;
			}
			set {
				this.__mt_webBrowser = value;
				this.SetNativeField("webBrowser", value);
			}
		}
	}
}
